# Generated by Django 3.1.2 on 2020-10-14 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '__first__'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='movie_actors',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
    ]
