# Generated by Django 3.1.2 on 2020-10-14 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviews_movie_actors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='movie_actors',
        ),
    ]
